### ISSUE TITLE
开启左侧边栏并打开新文件后右侧滚动条失效

### ISSUE THREAD

**Issue by Khrysoberyl** [PKM-er/Blue-Topaz_Obsidian-css#319]
如图，两个窗口并列展示时，当开启左侧边栏并打开一个新文件时，只有左侧的滚动条可以拖动，右侧的没有焦点。当收起左侧边栏后，两个窗口都可以正常拖动。但新打开一个文件后又只有左侧滚动条可以拖动。

https://user-images.githubusercontent.com/77917024/172098432-f415aa6f-ffce-4289-a703-4191f691d9bb.mp4

已更新最新版，仅在Style Manager中将右侧边栏更改为Fixed，未作其它样式调整。

**Comment by whyt-byte** [comment]
未能复现，请更新主题，并关闭除style settings以外插件，检查问题是否依旧。

**Comment by Khrysoberyl** [comment]
重启Obsidian后变为右侧滚动条任何时候都不可用，鼠标移上无反应，关闭插件及更新主题未能解决问题。
我正在使用旧版编辑器，我发现将旧版编辑器选项关闭后重启Obisidian可以解决问题，因此可能是旧版编辑器问题？请问能否保持对旧版编辑器的兼容？
![image](https://user-images.githubusercontent.com/77917024/173695266-12c3117a-92e6-4a85-b8b6-700f6646e5de.png)

**Comment by whyt-byte** [comment]
请检查软件安装版本，低于0.14的话，请使用安装包重新安装
