### ISSUE TITLE
External link icon is hiding when hovered in reading mode

### ISSUE THREAD

**Issue by slipdem** [PKM-er/Blue-Topaz_Obsidian-css#429]
External link icon is hiding when hovered in reading mode in both theme colors.
![Screen Recording 2022-10-22 at 00 17 10](https://user-images.githubusercontent.com/12971337/197290809-10bf9056-44db-4684-9855-9079ce9a8064.gif)

**Comment by cumany** [comment]
Update the theme, it has been fixed
