### ISSUE TITLE
对1.2背景设置功能的小建议

### ISSUE THREAD

**Issue by 76563** [PKM-er/Blue-Topaz_Obsidian-css#498]
3F及其他协作者你好！我一直很喜欢blue topaz主题，因为它的自定义功能非常丰富，谢谢你们一直以来的付出！不过在使用过程中，我也遇到了一点小小的问题😶‍🌫️：
![image](https://user-images.githubusercontent.com/106232184/211564139-98ff398a-081c-4d5c-9ae3-c1428719cb66.png)

比如在1.2的背景设置中，我发现1.2.1,1.2.3,1.2.4都有custom自定义背景图像的选项，唯独1.2.2的笔记背景中没有，虽然它内载了非常强大的随机联网背景，但是我还是想使用自己的背景，希望您能提供这个选项🥺
并且我注意到在两周前的改动中，blue topaz在尝试删减主题体积，如果能为1.2.2增加自定义图片的话，那就可以简化掉其下的类笔记功能和1.2.2.1设置。比如 https://www.transparenttextures.com/ 这个网站就有非常多的底纹材质样式，用户能自己在素材网上寻找想要的纸张背景，而不再拘泥于主题的内嵌。

另外我希望能为1.2.4文件栏背景增加一个透明度调节，就像1.2.3命令面板那样。如图所示，我在文件栏设置了一张兔子的图片，但它被透明化了，以至于存在感很弱。
![image](https://user-images.githubusercontent.com/106232184/211567978-653dce5e-c8b6-4cdb-9010-b7ed8ad9b32c.png)
![image](https://user-images.githubusercontent.com/106232184/211568401-cc612b6b-b1ab-4ada-b4bc-d8b6c2f5bc0d.png)

再次致以感谢！

**Comment by whyt-byte** [comment]
谢谢你对于主题的喜欢！原计划是会做自定义笔记背景的，但是由于各种事情耽误了。之后有时间会加上这个设置。你的建议很好，我们会进行相应修改，谢谢。

另外，类笔记背景设置其实跟笔记背景设置不是完全的互斥关系，而是可以叠加设置的。
