### ISSUE TITLE
代码块第几行（line number）显示错误

### ISSUE THREAD

**Issue by shizidushu** [PKM-er/Blue-Topaz_Obsidian-css#511]
如果代码块的行数过多时，会显示出错，如下图所示

![code line](https://user-images.githubusercontent.com/13694980/219423248-0dc04fa7-6964-455d-a46a-ca352de02eb7.png)

**Comment by cumany** [comment]
在实时预览下 因为Obsidian的机制是 加载到视图的时候才刷新数据 这时候会重新编号 所以纯css无法解决这个问题
