### ISSUE TITLE
List in embedded note is truncated

### ISSUE THREAD

**Issue by 64er** [PKM-er/Blue-Topaz_Obsidian-css#516]
When I create list with more than 9. items, the items 10., 11., ... are displayed correctly in the note. If I embed this note with ![[...]] in another note, then the first digit of 10., 11., etc. is cut off and there is 0. 1.

![Screenshot_20230306_063847_Obsidian](https://user-images.githubusercontent.com/4814508/223439073-d443fc59-cf3d-4999-a647-8f383c496cbe.jpg)

**Comment by cumany** [comment]
新版主题应该已经解决了这个问题

**Comment by 64er** [comment]
I tried to update the theme but there is no new version. In the installed version the error still exists!

**Comment by cumany** [comment]
![image](https://github.com/PKM-er/Blue-Topaz_Obsidian-css/assets/42957010/2f1bef15-a909-41f5-80af-d3dd0de88f64)

**Comment by 64er** [comment]
I have found the error. I have created a test vault like in your example. On my MacBook (Obsidian Desktop) it is displayed correctly. On my Galaxy Tab S7+ (Obsidian Mobile) the first digit is still cut off.

I used the same test vault with the same notes both times.
