### ISSUE TITLE
[BUG] Transparency issues

### ISSUE THREAD

**Issue by zanodor** [PKM-er/Blue-Topaz_Obsidian-css#517]
Hi mate,

Unfortunately, I can only use Simplicity in light mode (which is nice but too creamy or hazy for me), because on the other ones I run into transparency issues when right-clicking into a link.  
I don't think I could recall installing a snippet that would mess it up.  
Any ideas?  

I made a recording:  
https://share.icloud.com/photos/00aPc8aD9KrpEoiD_nIRbujlA

Cheers

**Comment by cumany** [comment]
try  the new theme
