### ISSUE TITLE
how to change the color of backticks enclosed region in "edit" mode?

### ISSUE THREAD

**Issue by swang203** [PKM-er/Blue-Topaz_Obsidian-css#528]
Hello, 
Thanks for building this wonderful plug-in. 
I have a question, and I'm mainly only using edit mode for my work. 
And the edit mode coloring is an important thing for me. 
Currently, the backticks enclosed region is colored as bold yellow with a dark grey background. 
How to change that? I've checked the "Style Settings" but most of the color settings in the code box are for read mode. 

Can you guys help me to point out where I should start to customize my own color style in "Edit" mode?

Thanks for your help!

**Comment by cumany** [comment]
![image](https://github.com/PKM-er/Blue-Topaz_Obsidian-css/assets/42957010/4411a1a7-f295-4c9f-9885-24acc131c033)
Sorry for the late reply. The styling of inline code is in the 2.3.9.2  with style setting
