### ISSUE TITLE
[Broken look](See screenshot) Collapsable icon is obscured in global search results.

### ISSUE THREAD

**Issue by Ali-C-Ila** [PKM-er/Blue-Topaz_Obsidian-css#531]
This also makes it hard to click the button. 
![image](https://github.com/whyt-byte/Blue-Topaz_Obsidian-css/assets/56729449/5ebead4a-4995-4adb-989d-91cda3b6b97f)

Appreciation for your great theme and constant update!

## debug info
Reproduced in a new sandbox.

SYSTEM INFO:
	Obsidian version: v1.3.4
	Installer version: v1.2.8
	Operating system: Windows 10 Home 10.0.22621
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Blue Topaz v20230509
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 0
	Plugins enabled: 0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.

**Comment by cumany** [comment]
Sorry for the late reply. The new version of the theme has fixed this issue
