### ISSUE TITLE
能否优化一下，使得BT主题支持关闭表格渲染样式

### ISSUE THREAD

**Issue by FeiLZX3Km** [PKM-er/Blue-Topaz_Obsidian-css#534]
使用BT主题后表格会直接拉宽到笔记文字所及的两端，哪怕是在列数极少、字数极少的情况下，也会如此。这样会很难看，也会使人阅读不便。
虽然可以手动将表格列宽恢复到合适大小，但是一旦关闭笔记再重新打开，表格就又会变成很宽的样子。
因此，我希望能够通过BT主题设置来关闭表格渲染样式。但是我找了所有设置项、或者在网上搜索相关的CSS片段，也没能找到解决方法。

**Comment by cumany** [comment]
![image](https://github.com/PKM-er/Blue-Topaz_Obsidian-css/assets/42957010/5d47da09-5a34-4bad-91eb-e913c1028650)
下个版本主题支持
