### ISSUE TITLE
编辑模式下，同时高亮和加粗文本，就只有高亮

### ISSUE THREAD

**Issue by chenhd9** [PKM-er/Blue-Topaz_Obsidian-css#538]
不知道是不是使用有误。如下图所示，当单独高亮和加粗时，都没有问题，但是在同时进行高亮和加粗时，就只剩绿色的高亮了，文本并没有加粗。。大佬看下哈
![image](https://github.com/whyt-byte/Blue-Topaz_Obsidian-css/assets/49526737/5153c321-63bc-4d28-a0a8-017340529d2b)

**Comment by chenhd9** [comment]
不过如果在阅读模式下，就是正常的。

**Comment by cumany** [comment]
这个颜色是属于 多彩高亮语法 可以自定义颜色的 也可以在这里取消
![image](https://github.com/PKM-er/Blue-Topaz_Obsidian-css/assets/42957010/f9ce7570-26bc-4165-98a6-442f8768193d)
