### ISSUE TITLE
用了主题后，table表的头部要多加个换行才能正常渲染成表格

### ISSUE THREAD

**Issue by obqrn** [PKM-er/Blue-Topaz_Obsidian-css#541]
用了主题后，table表的头部要多加个换行才能正常渲染成表格

（这里这行，如果不是换行则有问题）
| ip                | 说明    |
| ------------- | ------ |
| 192.168.8.1  |  123   |

比如这个，表格头的上一行没有换行，无法正常渲染

**Comment by cumany** [comment]
这是ob 编辑器的机制 主题无法改变
