### ISSUE TITLE
请教，我怎么也找不到这个颜色如何修改

### ISSUE THREAD

**Issue by zhl111** [PKM-er/Blue-Topaz_Obsidian-css#542]
查询关键词的颜色很不显眼，我想改的鲜艳一些，找不出。它又和search的颜色不是一个设置
![image](https://github.com/whyt-byte/Blue-Topaz_Obsidian-css/assets/29135984/0722b978-c4cc-4599-9a87-af5cf6fa37c8)

这个我能改
![image](https://github.com/whyt-byte/Blue-Topaz_Obsidian-css/assets/29135984/5a9d8db3-a5c0-4886-9589-9e0464347960)
这个我改不过来
![image](https://github.com/whyt-byte/Blue-Topaz_Obsidian-css/assets/29135984/16f28612-74e7-4ed6-bafd-5a6ac882e91c)
看css却是一个
![image](https://github.com/whyt-byte/Blue-Topaz_Obsidian-css/assets/29135984/604912e1-43d7-4507-973b-32fece0330e9)

**Comment by cumany** [comment]
![image](https://github.com/PKM-er/Blue-Topaz_Obsidian-css/assets/42957010/b7d79719-8c00-4c1d-add4-ca4e59c69500)
下个版本即可生效
