### ISSUE TITLE
新版本彩色文件标题失效

### ISSUE THREAD

**Issue by hipedo** [PKM-er/Blue-Topaz_Obsidian-css#545]
![image](https://github.com/PKM-er/Blue-Topaz_Obsidian-css/assets/89086812/d3807b69-9ed9-40a1-8ef3-28e866ccce6f)
在自己的笔记库和示例库中调试均无法按调出彩色文件标题，彩色文件夹还是可以用的
就算是截取片段也不能显示彩色标题，不知道发生了什么，挨个插件测试中

**Comment by cumany** [comment]
下个版本修复
