### ISSUE TITLE
[bug]设置字体为霞鹜文楷后,标题的字体依旧没有改变

### ISSUE THREAD

**Issue by a15355447898a** [PKM-er/Blue-Topaz_Obsidian-css#547]
![image](https://github.com/PKM-er/Blue-Topaz_Obsidian-css/assets/62456287/7efa359e-7de7-4a86-8143-9b91e2a08f32)

我已经在设置里面全部选择了"霞鹜文楷"

但是标题的字体依旧没有改变

![image](https://github.com/PKM-er/Blue-Topaz_Obsidian-css/assets/62456287/40b1e276-fa0e-459f-a179-1c6192c64cd9)

上图中可以明显看到"定义"这两个字在正文与标题中的字体不一样

**Comment by cumany** [comment]
style setting 中可以单独对标题字体设置  
![image](https://github.com/PKM-er/Blue-Topaz_Obsidian-css/assets/42957010/559ffe3b-5c3b-4ede-bc31-76748a37b5ae)
里面的内容 写成 'LXGW WenKai','霞鹜文楷 GB'
