### ISSUE TITLE
1.28之后版本如何使用本地图片作为背景？

### ISSUE THREAD

**Issue by Noctune** [PKM-er/Blue-Topaz_Obsidian-css#550]
1.28版本去年了app://local支持，要如何才能设置本地图片作为笔记背景？尝试官方的方案无果。
If you were relying on app://local for functionality within your plugin, you should use vault.getResourcePath(file: TFile) and vault.adapter.getResourcePath(vaultPath: string) as a replacement. These also works on mobile.

**Comment by cumany** [comment]
只能使用 图床或者把图片转为 base64
