### ISSUE TITLE
希望这个tag里的emoji可以保留原来的颜色

### ISSUE THREAD

**Issue by yoghurtdewdew** [PKM-er/Blue-Topaz_Obsidian-css#552]
<img width="468" alt="image" src="https://github.com/PKM-er/Blue-Topaz_Obsidian-css/assets/63794438/79570046-e5d5-4fba-a37e-e6d5b21171d6">

比如这个是蓝色，输入的时候看到一会儿变紫色一会儿变绿色一会儿是红色，会让我有点不知所措

希望这个tag里的emoji可以保留原来的颜色，我蛮喜欢colorful的这种感觉，但是因为使用到不同颜色的emoji作为tag，发现一个tag的颜色会变成很多种，会让我有点困扰

可以让tag的颜色跟随emoji，起码不让有颜色的emoji的颜色跟随tag

**Comment by cumany** [comment]
彩虹标签会按标签顺序显示颜色 无法判断标签内容，所以无法区分是否表情还是文字。

**Comment by yoghurtdewdew** [comment]
啊我的意思是，标签中的 emoji 比如📕可以不随着标签变色，不然会把📕变成上面的情况，当我还使用📘的时候，就会分不清是哪个标签啦

所以你的意思是，目前标签里文字是变色的？

**Comment by cumany** [comment]
是的 彩虹标签 本来就是变色的  除非你在style setting 的 tags 设置为其他类型的标签

**Comment by whyt-byte** [comment]
已增加tags选项
