### ISSUE TITLE
无法正常显示行内图片,这是托帕石的问题

### ISSUE THREAD

**Issue by tapeon01** [PKM-er/Blue-Topaz_Obsidian-css#556]
其他的主题都没有问题, obsidian原版也没有问题
但使用托帕石后行内图片会独占一行, 希望解决.

**Comment by cumany** [comment]
![image](https://github.com/PKM-er/Blue-Topaz_Obsidian-css/assets/42957010/9da4df33-bb41-49d6-8ec0-6f282cc55fcb)
style setting 设置中  使用ob默认图片开启即可
