### ISSUE TITLE
[BUG] Text of links change to different font in reading mode

### ISSUE THREAD

**Issue by Sinsinkuga** [PKM-er/Blue-Topaz_Obsidian-css#557]
Hello, hope you are well. My issue is with the links not conforming to chosen font in reading mode. The first picture is of the note in editing mode, where all text adheres to one font, and the second picture shows the same note in reading mode, where the text of the links change font.  

<img width="339" alt="Screenshot 2023-08-31 at 2 26 55 AM" src="https://github.com/PKM-er/Blue-Topaz_Obsidian-css/assets/143689573/8e042851-9d29-4ac2-83fd-48a362f050ae">

<img width="338" alt="Screenshot 2023-08-31 at 2 28 24 AM" src="https://github.com/PKM-er/Blue-Topaz_Obsidian-css/assets/143689573/9871655e-a9c1-426d-bd17-3388e2bb73c3">

I've used sandbox/default theme and it doesn't appear to have the same problem.

Thank you for your time, I hope to see a solution! This is a fantastic and lovely theme. Thank you so much for all your work!

**Comment by Postbenji** [comment]
Just found a possible solution for that today. Do you use the Style Settings plugin that allows you to tweak Blue Topaz? If you enable the toggle for "use obsidian default font-family" under 2.2.1 of the Style Settings Plugin, then it should use the same font for your links.

**Comment by Sinsinkuga** [comment]
Yes! that worked, thank you so so much!!
