### ISSUE TITLE
obsidian更新了properties，希望推出设置适配一下主题。

### ISSUE THREAD

**Issue by Kenry22** [PKM-er/Blue-Topaz_Obsidian-css#559]

**Comment by Ali-C-Ila** [comment]
示意圖：
![image](https://github.com/PKM-er/Blue-Topaz_Obsidian-css/assets/56729449/7abb9faa-da33-4088-a0d6-f2ce1f94035b)

具體來說我覺得可以新增 
- 顯示/不顯示 "add properties" 字樣
- 整理 "+"按鈕到properties旁邊
- 顯示/完全不顯示 properties
- 等等功能

**Comment by cumany** [comment]
新版主题已支持
