### ISSUE TITLE
为什么首行缩进的长度不一致啊……

### ISSUE THREAD

**Issue by RuJingTingShan** [PKM-er/Blue-Topaz_Obsidian-css#560]
![2023-09-13_00002](https://github.com/PKM-er/Blue-Topaz_Obsidian-css/assets/96676995/99c16cab-61b6-44a5-a2c2-7f6d87c00a31)
如图
手贱更新了一下到新版，突然首行缩进功能把我文档的排版全毁了，看的好别扭啊

**Comment by cumany** [comment]
已修复
