### ISSUE TITLE
使用该主题字体不等宽

### ISSUE THREAD

**Issue by STHxiao** [PKM-er/Blue-Topaz_Obsidian-css#561]
问题：
为了使各行间能严格对齐美观，已使用中英文混合等宽字体Sarasa gothic，如下图所示，默认主题下各行注释可严格对齐
![image](https://github.com/PKM-er/Blue-Topaz_Obsidian-css/assets/46336534/7a4158a2-ae89-4939-92cc-975efcf617ef)
但使用该主题后，不能对齐。
![image](https://github.com/PKM-er/Blue-Topaz_Obsidian-css/assets/46336534/74103414-afab-4b93-84c1-5c1cf235c2a4)

原因分析：
可能是空格不等宽了？

**Comment by whyt-byte** [comment]
已修复
