### ISSUE TITLE
Date time properties hidden

### ISSUE THREAD

**Issue by cristi-neagu** [PKM-er/Blue-Topaz_Obsidian-css#567]
Hello,

Looks like this theme doesn't display date and/or time properties. If I add such a property to the yaml section of a file, it simply does not show up. If you add a date time property, it only shows until you refresh the file, or if you're in live edit mode. In reading mode date time properties are hidden.

Thanks.

**Comment by cumany** [comment]
2.3.24 with style setting
![image](https://github.com/PKM-er/Blue-Topaz_Obsidian-css/assets/42957010/75acbbb4-87e6-43b7-a197-371992aa4354)
