### ISSUE TITLE
[BUG] broken link的頁面預覽出現黑色陰影

### ISSUE THREAD

**Issue by Ali-C-Ila** [PKM-er/Blue-Topaz_Obsidian-css#569]
如圖，broken link的頁面預覽右側出現黑色陰影，希望可以修正成一致的底色
(用預設主題無此現象)
![image](https://github.com/PKM-er/Blue-Topaz_Obsidian-css/assets/56729449/6c286e40-11c1-46a3-87fb-6abf282bed31)

**Comment by whyt-byte** [comment]
内测版本已修复，github没有确定发版时间
