### ISSUE TITLE
How to turn off translucent background colors?

### ISSUE THREAD

**Issue by HunzenVBA** [PKM-er/Blue-Topaz_Obsidian-css#570]
I am using Blue Topaz with Simplicity color palette by @cumany 
It is really nice but I have trouble reading with the translucent background colors like here:

Strange New World preview pane
![image](https://github.com/PKM-er/Blue-Topaz_Obsidian-css/assets/44619392/e10dae46-3356-40b9-b195-6fa64e382541)

Command palette
![image](https://github.com/PKM-er/Blue-Topaz_Obsidian-css/assets/44619392/d90ff853-5b39-4f42-a586-ad062760f974)

Settings panel
![image](https://github.com/PKM-er/Blue-Topaz_Obsidian-css/assets/44619392/e30eb3f1-8b70-4ce1-82b7-d4bfaeea4134)

I think I have to change the alpha value in hsla but I dont know how to find the correct variables/objects in the CSS  🤷

**Comment by cumany** [comment]
很抱歉回复晚了 最近版本的更新已修复这个问题
