### ISSUE TITLE
【功能需求】支持设置ob白板聚焦时的自动缩放倍数

### ISSUE THREAD

**Issue by aiyou9** [PKM-er/Blue-Topaz_Obsidian-css#572]
这是现在点击聚集按钮，自动放大的倍数
![image](https://github.com/PKM-er/Blue-Topaz_Obsidian-css/assets/15712822/0f89af35-2754-4e5b-8654-e91b43090a5f)
这是手动放大的最大倍数，希望，能在主题中给出，聚焦按钮，调用的自动缩放设置
![image](https://github.com/PKM-er/Blue-Topaz_Obsidian-css/assets/15712822/03950556-34dd-40c5-850f-7feeef45818d)

**Comment by whyt-byte** [comment]
css做不到
