### ISSUE TITLE
Network usage is prohibited for themes

### ISSUE THREAD

**Issue by joethei** [PKM-er/Blue-Topaz_Obsidian-css#574]
It appears that your theme uses network connections to load assets (e.g. fonts, icons, or images). This is prohibited by the official [Obsidian developer policies](https://docs.obsidian.md/Developer+policies) because themes should function completely locally.

You can bundle an asset for local use by using data URLs. [See this guide](https://docs.obsidian.md/Themes/App+themes/Embed+fonts+and+images+in+your+theme). 

Please let us know if you have any questions. Any themes that use network connections will be removed from the official directory in the first week of January 2024.

- the Obsidian team

**Comment by whyt-byte** [comment]
那就移除吧，正好我也不想去修你们在v1.5 insider版本里新增的问题。其实以后态度可以更敷衍一点、更强硬一点，毕竟是主题作者求着为你们写主题的，对吧！

顺便一提，发正式版的时候记得把无序列表的点和线对齐🙂

**Comment by windily-cloud** [comment]
> It appears that your theme uses network connections to load assets (e.g. fonts, icons, or images). This is prohibited by the official [Obsidian developer policies](https://docs.obsidian.md/Developer+policies) because themes should function completely locally.
> 
> You can bundle an asset for local use by using data URLs. [See this guide](https://docs.obsidian.md/Themes/App+themes/Embed+fonts+and+images+in+your+theme).
> 
> Please let us know if you have any questions. Any themes that use network connections will be removed from the official directory in the first week of January 2024.
> 
>     * the Obsidian team

done！
