### ISSUE TITLE
关于Heading标题样式问题

### ISSUE THREAD

**Issue by w1sd0m367** [PKM-er/Blue-Topaz_Obsidian-css#577]
为什么Heading标题仍然是默认字体样式？即使 我更改了全局的字体位LXWG

**Comment by cumany** [comment]
下个版本修复， 全局字体有限。不过如果相对某个标题单独指定字体 可以在 
![image](https://github.com/PKM-er/Blue-Topaz_Obsidian-css/assets/42957010/e0489e6d-70bb-4fb8-9e20-08002f20ae47)
这里shez设置
