### ISSUE TITLE
[BUG]代码块超过60行后下滑行号变为1

### ISSUE THREAD

**Issue by AllenLi-01** [PKM-er/Blue-Topaz_Obsidian-css#579]
如图
![image](https://github.com/PKM-er/Blue-Topaz_Obsidian-css/assets/73413064/c8946612-e6f9-4baf-ab2c-5ba27710a8f7)
官方自带的行号显示正常
![image](https://github.com/PKM-er/Blue-Topaz_Obsidian-css/assets/73413064/b818df52-14ae-4e11-8b3d-62076da28e8c)

环境：
windows11
Obsidian 1.5.8
Blue Topaz 2023112601

**Comment by cumany** [comment]
这是ob编辑器  懒加载造成的 通过css 暂时无法解决
