### ISSUE TITLE
無效連結的紅色底線 和顏色不搭配

### ISSUE THREAD

**Issue by Ali-C-Ila** [PKM-er/Blue-Topaz_Obsidian-css#581]
## 描述
如圖，最近無效連結的顏色和普通連結的顏色變得比較接近，和紅色的底線不太搭，和閱讀模式也不一致(底線跟字都是紅的)

把底線的顏色改的和文字一樣應該好一些? 歡迎提供其他想法。
![image](https://github.com/PKM-er/Blue-Topaz_Obsidian-css/assets/56729449/e626fc89-1b66-44de-b4eb-41531c094435)

## 使用情景
我個人在筆記中會預先用到不少無效連結(以便未來用quick switcher或wiki link)，所以對美觀影響蠻大的。
我自己是使用Topaz-nord色系。

**Comment by cumany** [comment]
感谢反馈。
相关的 未创建链接设置在这几个地方，可以恢复ob默认，也可以自定义颜色。
![image](https://github.com/PKM-er/Blue-Topaz_Obsidian-css/assets/42957010/de850c68-a527-4e7c-b5ac-46bf061df7e6)

当然，最近ob更新更改了 未创建链接的结构，主题显然还没有适配，下个版本主题也会适配。这样编辑模式跟阅读模式是保持一致的。
