### ISSUE TITLE
"funny header animation" 對 已折疊標題的"..." 沒有作用，導致重疊

### ISSUE THREAD

**Issue by Ali-C-Ila** [PKM-er/Blue-Topaz_Obsidian-css#582]
如圖
"funny header animation" 對 已折疊標題的"..." 沒有作用，導致標題文字與 "..." 重疊
![image](https://github.com/PKM-er/Blue-Topaz_Obsidian-css/assets/56729449/36b8dc32-5508-4253-b211-cdf1f6dd67ec)

比較：關閉 "funny header animation"，看起來就正常了
![image](https://github.com/PKM-er/Blue-Topaz_Obsidian-css/assets/56729449/51d61b8e-ad30-496c-a79c-88776fe32443)

**Comment by cumany** [comment]
新版已修复
