### ISSUE TITLE
4.19更新(1a5163c)后列表与标题之间异常间距

### ISSUE THREAD

**Issue by qyzl7** [PKM-er/Blue-Topaz_Obsidian-css#584]
版本：2024041901
设置：列表为默认设置

如下图，无序列表、有序列表的下间距没有正常显示，上间距正常

> ![1713527937462](https://github.com/PKM-er/Blue-Topaz_Obsidian-css/assets/22864299/f0898b2a-52a3-4ad7-b73c-3b0238575cf0)

另外，请问，列表与正文的间距应该如何修改，如下图红框

> ![1713528033409](https://github.com/PKM-er/Blue-Topaz_Obsidian-css/assets/22864299/194900ca-c555-4877-8d91-2deebd7947d9)

我试图修改列表行间距（line-height-list）、列表项间距（list-spacing-bt）产生的效果均是列表项间距缩小了

希望不吝赐教！如果需要进一步测试或提供我的使用设置请联系我

**Comment by cumany** [comment]
修复了 请更新主题    现在 2.3.2可以调整 列表与正文的间距了

**Comment by qyzl7** [comment]
已验证，更新后两个功能均正常使用。感谢您的回复
