### ISSUE TITLE
图片标题功能会导致排版错误

### ISSUE THREAD

**Issue by flamesky80** [PKM-er/Blue-Topaz_Obsidian-css#589]
1、新建一个Obsidian仓库
2、在外观下载并启用Blue Topaz主题
3、第三方插件 只 下载并启动 style settings，所有设置保持默认
4、直接在新建仓库的welcome页面操作，插入图片，按照 ![[img#left|Figure|size]]的格式写图片标题，排版就会显示错误。
![001](https://github.com/PKM-er/Blue-Topaz_Obsidian-css/assets/15180023/e58762b3-9776-427a-941f-0a155167a30a)

BlueTopaz是个好插件，一直在用。请解决这个问题，让插件更好！

**Comment by cumany** [comment]
![image](https://github.com/PKM-er/Blue-Topaz_Obsidian-css/assets/42957010/467d5ec5-5a77-4252-9853-ee466555ccb6)
这不是错误 这是图文混排的语法

**Comment by cumany** [comment]
使用 这个试试 ![[img#inl|Figure|size]]

**Comment by flamesky80** [comment]
了解了，原来我理解错误。
我还以为 #left|Figure|Size 里面的这个left/right/center/inl 只是单纯的指定“带标题的格式下”图片的位置。
非常感谢！！！
