### ISSUE TITLE
Having trouble applying custom backgrounds

### ISSUE THREAD

**Issue by fragilember** [PKM-er/Blue-Topaz_Obsidian-css#595]
Things I've tried: 
- Turn on Workspace background, turn off Note background and vice versa. Both didn't work. 
- Tried importing an online image as well as a local image. Both didn't work.
The online link to my image: https://pbs.twimg.com/media/F0_gwb9aAAA6K5N?format=jpg&name=900x900
The local link to my image: C:/Users/ADMIN/Desktop/F0_gwb9aAAA6K5N.jpg

I'm not sure if it's a syntax problem, since I tried following the instructions found [here](https://publish.obsidian.md/hub/02+-+Community+Expansions/02.05+All+Community+Expansions/Themes/Blue+Topaz) (see image 1). But nothing seemed to work. When I close the Style Settings interface, the background is weirdly bugged, where there would be weird imprints (see image 2). These imprints seem to be a bug.

![image 1](https://github.com/PKM-er/Blue-Topaz_Obsidian-css/assets/128197624/763cc783-83c7-49b2-a008-ee6d575d1ffc)
![image 2](https://github.com/PKM-er/Blue-Topaz_Obsidian-css/assets/128197624/974ec578-9460-4581-8cb4-74dd673b305c)

**Comment by aaaddd4747** [comment]
im having a simmilar issue, only internet images seem to work, i cant get any local files to load. quite annoying!

for your case, i suspect its because its a twitter hosted image you are trying to load, and twitter is being weird about it

**Comment by fragilember** [comment]
ty for the input, i'll look into it again!
