### ISSUE TITLE
编辑状态显示标题级别功能与行内代码冲突

### ISSUE THREAD

**Issue by gradypark86** [PKM-er/Blue-Topaz_Obsidian-css#603]
在开启显示标题级别功能后，若标题以行内代码（`）开头，则会出现显示错误，例如：

```markdown
## 测试
## `测试`
```

显示结果为：

<img width="305" alt="image" src="https://github.com/PKM-er/Blue-Topaz_Obsidian-css/assets/39909237/d912f4cb-bdd6-43d7-a23f-73044a5c64e6">

将”测试“用行内代码块包裹，则”H2“的标题级别会一起显示在行内代码块中。

**Comment by cumany** [comment]
下个版本 更新解决
