### ISSUE TITLE
更新之后侧边栏变得好难看

### ISSUE THREAD

**Issue by SadSock** [PKM-er/Blue-Topaz_Obsidian-css#604]
之前的侧边栏是这样的
<img width="299" alt="未命名" src="https://github.com/PKM-er/Blue-Topaz_Obsidian-css/assets/7643216/1d5d282b-4483-4bae-8dda-af634ca68b8a">
更新到最新之后，变成了这样
<img width="299" alt="image" src="https://github.com/PKM-er/Blue-Topaz_Obsidian-css/assets/7643216/7623952f-2c15-478d-8ea2-8535baf118ea">
这是发生了什么？

**Comment by Ali-C-Ila** [comment]
![image](https://github.com/PKM-er/Blue-Topaz_Obsidian-css/assets/56729449/1363ad0c-d6c8-4e26-9769-f42254ec0fef)

**Comment by SadSock** [comment]
已经解决了
