### ISSUE TITLE
隐藏左工具栏出问题

### ISSUE THREAD

**Issue by calmwaves111** [PKM-er/Blue-Topaz_Obsidian-css#610]
![36570b88d75bbd0baf7abe8000914f68](https://github.com/PKM-er/Blue-Topaz_Obsidian-css/assets/56907077/4e69c608-9d50-42aa-9f48-5d6e97201a6e)

我的bt主题，1.3左工具栏样式选择，Hide to left
有时候会变成这个样子，左工具栏出不来
但是重启ob又变好了，过了一阵又成这样了

ob是1.6.5，bt是最新版

**Comment by cumany** [comment]
没有复现出来 粘贴下 你的style setting配置 我看下是否存在配置冲突

**Comment by calmwaves111** [comment]
![image](https://github.com/user-attachments/assets/d60d6ac1-3a9b-4449-a168-cfd7023e3fb6)

复现步骤

打开沙箱库
安装 another quick switcher，style setting
安装blue topaz主题
外观里基础颜色改为深色
style setting 里1.2.1开启工作页面背景，dark mode下选in the sky
1.3左工具栏选hide to left
```json
{
  "blue-topaz-theme@@left-ribbon-style": "hide-left-ribbon",
  "blue-topaz-theme@@background-settings-workplace-background-image": true
}
```

然后运行命令【Another QuickSwitcher:Header floating search in file】

可能一开始这个悬浮框在左边，不会出现bug
先运行【重新加载Obsidian（不保存当前编辑内容）】，再重试【Another QuickSwitcher:Header floating search in file】，就有可能出现bug

**Comment by calmwaves111** [comment]
我现在可以确定，和hide to left没关系，只要改成深色模式，然后开启工作区背景，运行【Another QuickSwitcher:Header floating search in file】就有可能出现这个bug

**Comment by cumany** [comment]
更新主题 再试试 应该解决了

**Comment by calmwaves111** [comment]
ok没问题了
