### ISSUE TITLE
最新版本移出文件夹箭头不生效

### ISSUE THREAD

**Issue by eryajf** [PKM-er/Blue-Topaz_Obsidian-css#626]
我下午升级了最新版本，目前文件夹有一些重叠，想着移除箭头，但是点击之后没有生效。

<img width="87" alt="image" src="https://github.com/user-attachments/assets/122c299f-7c24-4403-9750-65e318910f9c">

**Comment by decetion** [comment]
> 我下午升级了最新版本，目前文件夹有一些重叠，想着移除箭头，但是点击之后没有生效。
> 
> <img alt="图像" width="87" src="https://private-user-images.githubusercontent.com/33259379/378070669-122c299f-7c24-4403-9750-65e318910f9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzNDc1OTEsIm5iZiI6MTcyOTM0NzI5MSwicGF0aCI6Ii8zMzI1OTM3OS8zNzgwNzA2NjktMTIyYzI5OWYtN2MyNC00NDAzLTk3NTAtNjVlMzE4OTEwZjljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE5VDE0MTQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2NjQwYWFjMDdiMWViNDgxZTkyMjZiOTQ1M2Y3MzNhYmFjZTIyYmNhNWM5ZjU5YzQ1MmUzYTY4NDlhZGNiYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fEKhkP2xyHUjQ_wOSuRwIZHSHYj1Y1qjNBxcHWPIdtY">

这个问题在obsidian官方论坛已解决：https://forum-zh.obsidian.md/t/topic/41468

移除箭头的css:
```
.nav-files-container .tree-item-icon.collapse-icon{
    display:none;
}
```
箭头左移的css:
```
.nav-files-container .tree-item-icon.collapse-icon {  
    margin-left: -35px; /* 将箭头往左移35像素，可以根据需要调整这个值 */  
}
```

**Comment by eryajf** [comment]
感谢，已OK
