### ISSUE TITLE
更新到1.7.4后文件夹不能正常显示

### ISSUE THREAD

**Issue by conanlm** [PKM-er/Blue-Topaz_Obsidian-css#627]
更新到1.7.4后文件夹不能正常显示
都挤在一起了

![Pasted image 20241022102430](https://github.com/user-attachments/assets/8d6024bc-ed98-4ecb-a3e8-0c2c56d18326)

**Comment by KatherineZL** [comment]
我的也是诶

**Comment by shileiye** [comment]
同样，求更新

**Comment by imrehg** [comment]
I _think_ I have the same issue, the little mark pointing right or down (as the list is collapsed or expanded) is overlapping with the folder name. The same on Linux and on the Android version of Obsidian.

Collapsed:

![blue_topaz1](https://github.com/user-attachments/assets/3e535a72-fcfb-41b8-991e-f646ad34a980)

Expanded:

![blue_topaz2](https://github.com/user-attachments/assets/d4fb2c27-0f99-4f33-8e0b-374e323bc4bb)

**Comment by fewsh-son** [comment]
I tried the following steps and it worked:
Style Settings -> Blue Topaz Theme -> 2. Detail settings -> 2.3.3 Folder
<img width="787" alt="Screenshot 2024-10-31 at 11 00 31" src="https://github.com/user-attachments/assets/a52afebc-38fe-4897-a374-bd3adba95010">
<img width="294" alt="Screenshot 2024-10-31 at 11 06 05" src="https://github.com/user-attachments/assets/5a0437f3-7548-458f-8b04-c22e5facd8be">

**Comment by fewsh-son** [comment]
> I tried the following steps and it worked: Style Settings -> Blue Topaz Theme -> 2. Detail settings -> 2.3.3 Folder <img alt="Screenshot 2024-10-31 at 11 00 31" width="787" src="https://private-user-images.githubusercontent.com/130850338/381820670-a52afebc-38fe-4897-a374-bd3adba95010.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNDg0MDcsIm5iZiI6MTczMDM0ODEwNywicGF0aCI6Ii8xMzA4NTAzMzgvMzgxODIwNjcwLWE1MmFmZWJjLTM4ZmUtNDg5Ny1hMzc0LWJkM2FkYmE5NTAxMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQwNDE1MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNjk3MDI2NjI5MjY4ZWJlMGNlMzNjZGY2ZDlkNjQ4YTJiYWFlOTQyMDllOTBiNDc4ZWZkMDU3MTI3NmEwYjc2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.us8b7Xv6Q-RsbezEcXf7mHOlfU_pizUcyHB0EfQ6iE4"> <img alt="Screenshot 2024-10-31 at 11 06 05" width="294" src="https://private-user-images.githubusercontent.com/130850338/381820742-5a0437f3-7548-458f-8b04-c22e5facd8be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNDg0MDcsIm5iZiI6MTczMDM0ODEwNywicGF0aCI6Ii8xMzA4NTAzMzgvMzgxODIwNzQyLTVhMDQzN2YzLTc1NDgtNDU4Zi04YjA0LWMyMmU1ZmFjZDhiZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQwNDE1MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OGM0YWU3OWFjMGNlN2FhMzZjMDNiNGY1ZjY0NzIzNDM4MTkxNDU1N2YzOTVjNzc3MDllZjNjNWI3ZTM5MTcyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.DrzxFQeg8CQYwiz7oidOjZhGPI1mMBwfpPfwT9FwrE0">

@conanlm @shileiye @KatherineZL @imrehg

**Comment by a-voyager** [comment]
> > I tried the following steps and it worked: Style Settings -> Blue Topaz Theme -> 2. Detail settings -> 2.3.3 Folder <img alt="Screenshot 2024-10-31 at 11 00 31" width="787" src="https://private-user-images.githubusercontent.com/130850338/381820670-a52afebc-38fe-4897-a374-bd3adba95010.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNDg0MDcsIm5iZiI6MTczMDM0ODEwNywicGF0aCI6Ii8xMzA4NTAzMzgvMzgxODIwNjcwLWE1MmFmZWJjLTM4ZmUtNDg5Ny1hMzc0LWJkM2FkYmE5NTAxMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQwNDE1MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNjk3MDI2NjI5MjY4ZWJlMGNlMzNjZGY2ZDlkNjQ4YTJiYWFlOTQyMDllOTBiNDc4ZWZkMDU3MTI3NmEwYjc2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.us8b7Xv6Q-RsbezEcXf7mHOlfU_pizUcyHB0EfQ6iE4"> <img alt="Screenshot 2024-10-31 at 11 06 05" width="294" src="https://private-user-images.githubusercontent.com/130850338/381820742-5a0437f3-7548-458f-8b04-c22e5facd8be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNDg0MDcsIm5iZiI6MTczMDM0ODEwNywicGF0aCI6Ii8xMzA4NTAzMzgvMzgxODIwNzQyLTVhMDQzN2YzLTc1NDgtNDU4Zi04YjA0LWMyMmU1ZmFjZDhiZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQwNDE1MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OGM0YWU3OWFjMGNlN2FhMzZjMDNiNGY1ZjY0NzIzNDM4MTkxNDU1N2YzOTVjNzc3MDllZjNjNWI3ZTM5MTcyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.DrzxFQeg8CQYwiz7oidOjZhGPI1mMBwfpPfwT9FwrE0">
> 
> @conanlm @shileiye @KatherineZL @imrehg

couldnt see the screenshots you uploaded. HTTP ERROR 404

**Comment by a-voyager** [comment]
我这边试了在 Style Settings 中的 2.3.3 "移除文件夹图标（折叠图标）"，关闭之后可以了
