### ISSUE TITLE
Folder arrow does not disappear

### ISSUE THREAD

**Issue by Ono-va-ne** [PKM-er/Blue-Topaz_Obsidian-css#631]
There is a folder arrow on the folder icon, which is not very pleasant to look at.

- Obsidian v1.7.4
- Blue Topaz v2024071502
### How to reproduce:
Style settings > Detail settings > Element styles > Foled > Active Folder Icons > **True**; Folder Icons w/o arrows (Collapse Indicator) > **True**

![изображение](https://github.com/user-attachments/assets/a2a825d8-5c35-470e-a181-61aa495548f5)

**Comment by cumany** [comment]
ver 2021110601 fixed
